###
POST  http://localhost:5000/dog/ HTTP/1.1
Content-Type: application/json

{
{
 "message": "<url received from the Dog CEO API>",
 "status": "success"
}
}

###
GET http://localhost:5000/dog/hound HTTP/1.1

###
GET http://localhost:5000/dog/673dbac0fe3ec4db0293565a  HTTP/1.1

###
PUT  http://localhost:5000/dog/673dbac0fe3ec4db0293565a HTTP/1.1
Content-Type: application/json

{
    "Breed": "DASCHUND",
    "done": true
}

###
DELETE http://localhost:5000/dog/673d6224649f34ef262d695b HTTP/1.1


###
GET http://localhost:5000/dog/breed/hound HTTP/1.1

###

###
GET https://dog.ceo/api/breed/hound/images/random HTTP/1.1

###
